project_id = "tgbskrfbyvbigpxcbyim"

[functions.admin-stats]
verify_jwt = false

[functions.upscale-image]
verify_jwt = false

[functions.notify-whatsapp]
verify_jwt = false

[functions.resolve-download]
verify_jwt = false
